### ISSUE TITLE
Core support for JSON-LD

### ISSUE THREAD

**Issue by nazar-pc** [nazar-pc/CleverStyle-CMS#7]
http://updates.html5rocks.com/2015/03/creating-semantic-sites-with-web-components-and-jsonld as reference for using JSON-LD with WebComponents.
JSON-LD structure will likely be available as `cs.jsonld` on frontend.

**Comment by ParkFramework** [comment]
Мы так же планируем переписать JSON трафик в формат JSON-LD, использую словарь schema.org.

Проблема заключается в том что нам необходимо передавать дополнительные свойства которых нет в словаре schema.org, мы не можем отказаться от этих ключей потому что там нужная техн информация, которая используется в логике работы наших AJAX сайтов.

Вопрос, наличия свойств которых нет в словаре schema.org, создаст проблемы для индексации AJAX сайтов, или поиск бот будет просто игнорировать свойства которых он не знает и на индексацию это не повлияет, как вы планируете решать эту проблему?

**Comment by nazar-pc** [comment]
Структура БД для модулей уже существует и работает, для API я планирую оставить всё как есть.

Была мысля описывать в каком-то формате трансформацию БД->JSON-LD на сервере и обратно на фронтенде.
Желательно, чтобы это был какой-то универсальный JSON, который можно было использовать для преобразования в оба направления.

Как при этом поступать с полями, которые не присутствуют в словаре пока не задумывался, не копал в этом направлении. Разве там нет мозможности добавлять пользовательские свойства? На сколько я помню там можно создавать собственные словари.

Вопрос интересный, если есть желание - можем найти какое-то общее решение, раз имеем схожие цели.

**Comment by ParkFramework** [comment]
Очень рекомендую посмотреть на PostgeSQL 9.4 и новый РНР драйвер pq
https://pecl.php.net/package/pq
В нем есть возможность получения данных в нативных РНР типах, int, float, колонки JSONB в виде массива - это очень удобно.

Кастом поля в JSON-LD нарушают весь смысл JSON-LD потому что он придуман для того чтобы каждое поле имело свою семантику, можно использовать свои словари, но их игнорирует анализатор goole и выдает ошибку:

```
<script type="application/ld+json">
{
	"@context": 
    {
    "@vocab":"http://schema.org/",
    "data": "http://my-data.org/"
    },
	"@type": "WebPage",
	"offers": 
	[
		{
			"@type": "Offer",
			"price" : 500,
            "data:sortField": "rate"
		}
	]
}
</script>
```
https://developers.google.com/structured-data/testing-tool/
Выдаст ошибку: ``Свойство http://my-data.org/sortField недопустимо для объекта типа Offer.``

Суппорт google молчит насчет кастом полей, но это важно, потому что если они ломают семантику это поломает индексацию сайта.

**Comment by nazar-pc** [comment]
Как по мне было бы неплохо, если бы поисковик игнорировал кастомные поля, учитывал только то, что понимает. Тогда и ему было бы хорошо, и нам бы не пришлось данные дублировать.
Мне пока сложно что-то сказать по этому поводу, ещё не углублялся в тему.

**Comment by ParkFramework** [comment]
Да, но наличия неопределенных полей в JSON-LD, это тоже самое что неопределенные теги в HTML, они игнорируется браузерами, но есть риск что в новых версиях HTML появятся эти теги и будут иметь совсем другое поведения и семантику.

В веб-компонентах эту проблему решили спец символов тире, думаю в JSON-LD тоже нужно идти таким путем.

Я пока что вижу два варианта:
1. Правильный.
По умолчанию указывать словарь schema.org, для кастом полей указать второй словарь и дать ему названия, например data, тогда все кастом поля должны начинаться с префикса data.
Например вот так 
```
<script type="application/ld+json">
{
    "@context": 
    {
    "@vocab":"http://schema.org/",
    "data": "http://example.com/api/"
    },
    "@type": "WebPage",
    "offers": 
    [
        {
            "@type": "Offer",
            "price" : 500,
            "data:sortField": "rate"
        }
    ]
}
</script>
```
Это означает что описания свойства sortField, описано по адресу ``http://example.com/api/sortField`` это удобно и там всегда можно прочить семантик описания этого поля.

2. Костыльный.
Все кастом поля класть в отдельный блок ``@context``, вот так:

```
<script type="application/ld+json">
{
    "@context": "http://schema.org/",
    "@type": "WebPage",
    "offers": 
    [
        {
            "@type": "Offer",
            "price" : 500,
            "@context":
            {
              "data:sortField": "rate"
            }
        }
    ]
}
</script>
```
Google анализатор ругаться не будет, но это грязный хак :)

Если вы найдете, лучшее решения, напишите мне будет интересно узнать.

**Comment by nazar-pc** [comment]
Читаю официальную спецификацию, пока прочел примерно 40%, вот пример с кастомными полями:
```
{
	"@context"     : {
		"@base"        : "http://schema.org",
		"custom_field" : ""
	},
	"@type"        : "Organization",
	"url"          : "http://www.your-company-site.com",
	"contactPoint" : [
		{
			"@type"       : "ContactPoint",
			"telephone"   : "+1-401-555-1212",
			"contactType" : "customer service"
		}
	],
	"custom_field" : "Some value"
}
```
То есть по сути, мы берем ту же структуру, что у нас была раньше и добавляем поля `@context` и `@type`. Поля, который в исходных данных не ложатся на словарь, либо вообще какие-то технические и не интересны поисковику можно исключить из обработки, как я сделал это с `custom_field`, Google нормально такое воспринимает.
Как дочитаю до конца ещё отпишусь, может какие новые идеи придут в голову.

**Comment by nazar-pc** [comment]
Хм... к стати, если просто добавить кастомное поле - по спецификации оно ОБЯЗАНО быть проигнорировано. То есть его не обязательно явно прятать, можно просто добавить:
```json
{
    "@context"     : {
        "@base"        : "http://schema.org",
        "custom_field" : ""
    },
    "@type"        : "Organization",
    "url"          : "http://www.your-company-site.com",
    "contactPoint" : [
        {
            "@type"       : "ContactPoint",
            "telephone"   : "+1-401-555-1212",
            "contactType" : "customer service"
        }
    ],
    "custom_field" : "Some value"
}
```

**Comment by nazar-pc** [comment]
В целом, дочитал спецификацию - начал экспериментальную исплементацию. Для блога получается примерно такое в исходном коде готовой страницы (отформатировано для удобства):
```html
<article is="cs-blogs-post">
	<script type="application/ld+json">
		{
			"@context"       : {
				"content"        : "articleBody",
				"title"          : "headline",
				"comments_count" : "commentCount",
				"@vocab"         : "https:\/\/schema.org",
				"id"             : "",
				"user"           : "",
				"date"           : "",
				"path"           : "",
				"draft"          : "",
				"short_content"  : "",
				"sections"       : "",
				"tags"           : ""
			},
			"@type"          : "BlogPosting",
			"inLanguage"     : "uk",
			"author"         : {
				"@context" : "https:\/\/schema.org",
				"@id"      : "Профіль\/назар",
				"@type"    : "Person",
				"name"     : "nazarpc",
				"url"      : "@id",
				"image"    : "https:\/\/www.gravatar.com\/avatar\/3d67cc976284fd62356e2edd8a8dfc49?d=mm&s=&d=http%3A%2F%2Fcscms.org%2Fincludes%2Fimg%2Fguest.svg"
			},
			"keywords"       : [
				"CMS"
			],
			"image"          : [
				"http:\/\/cscms.org\/storage\/public\/Plupload\/2014-11-15\/21\/2_39085467abdc00e75.jpg",
				"http:\/\/cscms.org\/storage\/public\/Plupload\/2015-03-01\/08\/2_052154f2ac21d6849.jpg"
			],
			"id"             : "41",
			"user"           : "2",
			"date"           : "1416080424",
			"title"          : "Awesome article with image",
			"path"           : "Awesome_article_with_image",
			"content"        : "<p><img src=\"http:\/\/cscms.org\/storage\/public\/Plupload\/2014-11-15\/21\/2_39085467abdc00e75.jpg\" alt=\"\" width=\"600\" height=\"375\" \/><\/p>\r\n<p><!-- pagebreak --><\/p>\r\n<p><img src=\"http:\/\/cscms.org\/storage\/public\/Plupload\/2015-03-01\/08\/2_052154f2ac21d6849.jpg\" alt=\"\" width=\"800\" height=\"450\" \/><\/p>",
			"draft"          : "0",
			"short_content"  : "<p><img src=\"http:\/\/cscms.org\/storage\/public\/Plupload\/2014-11-15\/21\/2_39085467abdc00e75.jpg\" alt=\"\" width=\"600\" height=\"375\" \/><\/p>\r\n<p>",
			"sections"       : [
				"2"
			],
			"tags"           : [
				"26"
			],
			"comments_count" : 1
		}
	</script>
</article>
```
Это всё, что нужно от Backend-а для генерирования странички поста из блога.
Сначала идет маппинг существующих полей к словарю, остальные исходные поля помечаются для игнорирования.
В теле некоторые поля вставляются напрямую из БД, некоторые после пост-обработки. В коде (пока что) выглядит вот так:
```php
h::{'article[is=cs-blogs-post] script[type=application/ld+json]'}(
	_json_encode(
		[
			'@context'   =>
				[
					'content'        => 'articleBody',
					'title'          => 'headline',
					'comments_count' => 'commentCount'
				] + Json_ld::context_stub($post),
			'@type'      => 'BlogPosting',
			'inLanguage' => $L->clang,
			'author'     => Json_ld::Person($post['user']),
			'keywords'   => $tags,
			'image'      => $images
		] + $post
	)
)
```
`Json_ld` - это будет класс из одноименного нового модуля, `::context_stub()` как раз генерирует поля-заглушки для свойств, у которых нет маппинга к словарю. `::Person()` генерирует карточку пользователя на основании его id в системе.

**Comment by ParkFramework** [comment]
Да, можно объявить все кастом поля в @context, это рабочий вариант, спасибо.

Я сейчас занят другими делами, но когда освобожусь планировал создать тест сайт, в котором весь контент будет находится в JSON-LD.
Через дней 10 проверить выдачу гугла (site:example.com) там будет видно как гугл воспринимает такие страницы.

Есть масса всяких мелочей, например поле ``articleBody`` в нем не просто текст, там HTML разметка, мне интересно что будет в снипетах выдачи, текст без тегов или текст в нативном виде с тегами?

Возможно вам будет так же интересно создать свой тест сайт и проверить все на практике.

**Comment by nazar-pc** [comment]
Ну почему-же тестовый?) Будем на боевой выкладывать.
Модуль блогов переписывается, будет, по крайней мере, для пользовательской стороны, полностью на JSON-LD, [cleverstyle.org](http://cleverstyle.org) будет обновлен, там и будет видно.
Вот уже есть некоторое начало: https://github.com/nazar-pc/CleverStyle-CMS/commit/f1ba3e0a3c9aaa2b3b844e58e65d9896f3047a29#diff-af7a2c100a29215cf6a3ae7eaa301bf0R143, получить пост в JSON-LD формате уже можно, осталось веб-компонент написать для отображения, ну и ещё кое-что по мелочи.

**Comment by ParkFramework** [comment]
Тестовый сайт (домен) не жаль испортить и попасть под санкции гугла, на тест сайте можно проводить эксперементы, на боевом сайте такие эксперементы могут дорого стоить )

Насчет JSON-LD, которую вы генерите, есть маленькие корректировки, повторно указывать ``"@context" : "https://schema.org"`` ненужно достаточно указать в парент объекте, все чилдрены наследуют контекст, так же я не вижу смысла в ``"url" : "@id"`` если не указано поле ``url`` оно строится по значению ``@id"`` т.е спецификации заложена это поведения и дублировать его ненужно. Ну это так мелочи...

**Comment by nazar-pc** [comment]
Тестовый сайт это да, но если тест google покажет что всё хорошо - не виду риска, все основные поисковики при наличии JSON-LD обойдутся без дополнительных подстказок (в блоге там ещё Open Graph разметка генерируется для Facebook и подобных).

По поводу `@context` - знаю, это берется от `Json_ld::Person($post['user'])`, stand alone реализация, поэтому используется как есть, одна строчка - не большие накладные расходы, а вырезать её специально - это только запутывать код. При получении нескольких постов блога строится граф из постов, то есть разумные оптимизации структуры в наличии имеются.

На счёт `url` интересно, а можно какой-то линк на этот пункт, не нашел [здесь](http://www.w3.org/TR/json-ld/)?

**Comment by ParkFramework** [comment]
Я уже не помню где это конкретно описано, вообще весь JSON-LD строится на том что все ключи это юрл от контекста, @id - это идентификатор сущности, полное имя этого идентификатора это ``base_url + id``

Вот например, если вести этот код в гугл анализатор
https://developers.google.com/structured-data/testing-tool/
```
<script type="application/ld+json">
{
   "@context": "http://schema.org",
   "@type": "WebSite",
   "@id": "AAAAAAAAAAA"
}
</script>
```
он поймет его как
``WebSite:	http://www.example.com/AAAAAAAAAAA``

**Comment by nazar-pc** [comment]
Я понимаю, но всё же в schema.org есть отдельное свойство `url` в [Thing](http://schema.org/Thing), вот я и посчитал нужным явно указать его. По стандарту `@id` это что-то глобально-уникальное, но не обязательно то же, что и url.

P.S. Берите всё, что начинается с `@` в `` ` ``, иначе вы куче людей уведомления присылаете)

**Comment by ParkFramework** [comment]
Указывать `url` нужно если оно не равняется `@id`, в вашем случаи они равны, то что вы дублируете это не криминал, но можно не дублировать.

Насчет тест сайта, проверять выдачу на домене cleverstyle.org не очень хорошо, потому что контент сайтв уже есть в индексе гугла и не факт что через 10 дней его выдача будет основана на JSON-LD.
Для чистоты эксперимента лучше сделать новый домен, например json-ld.cleverstyle.org и смотреть на его выдачу, это будет более чистый эксперимент.

**Comment by nazar-pc** [comment]
Ну вот, пока что готова страница поста, в исходнике страницы получилось так (JSON на самом деле в одну строку):
```html
<article can_delete="1" can_edit="1" comments_enabled="1" is="cs-blogs-post">
	<script type="application/ld+json">
		{
		    "@context": {
		        "content": "articleBody",
		        "title": "headline",
		        "comments_count": "commentCount",
		        "tags": "keywords",
		        "datetime": "",
		        "sections_paths": "",
		        "tags_paths": "",
		        "@vocab": "https:\/\/schema.org",
		        "id": "",
		        "user": "",
		        "date": "",
		        "path": "",
		        "draft": "",
		        "short_content": "",
		        "sections": ""
		    },
		    "@id": "http:\/\/cscms.org\/uk\/Блоги\/Awesome_article_with_image:41",
		    "@type": "BlogPosting",
		    "articleSection": [
		        "Вкладена категорія"
		    ],
		    "author": {
		        "@context": "https:\/\/schema.org",
		        "@id": "http:\/\/cscms.orgprofile\/назар",
		        "@type": "Person",
		        "name": "nazarpc",
		        "url": "http:\/\/cscms.orgprofile\/назар",
		        "image": "https:\/\/www.gravatar.com\/avatar\/3d67cc976284fd62356e2edd8a8dfc49?d=mm&s=&d=http%3A%2F%2Fcscms.org%2Fincludes%2Fimg%2Fguest.svg"
		    },
		    "datePublished": "2014-11-15T21:40:24+02:00",
		    "image": [
		        "http:\/\/cscms.org\/storage\/public\/Plupload\/2014-11-15\/21\/2_39085467abdc00e75.jpg",
		        "http:\/\/cscms.org\/storage\/public\/Plupload\/2015-03-01\/08\/2_052154f2ac21d6849.jpg"
		    ],
		    "inLanguage": "uk",
		    "url": "http:\/\/cscms.org\/uk\/Блоги\/Awesome_article_with_image:41",
		    "datetime": "Субота, 15 Листопада 2014, 21:40",
		    "sections_paths": [
		        "http:\/\/cscms.org\/uk\/Блоги\/Розділ\/Деяка_категорія\/Вкладена_категорія"
		    ],
		    "tags_paths": [
		        "http:\/\/cscms.org\/uk\/Блоги\/Тег\/CMS"
		    ],
		    "id": "41",
		    "user": "2",
		    "date": "1416080424",
		    "title": "Awesome article with image",
		    "path": "Awesome_article_with_image",
		    "content": "<p><img src=\"http:\/\/cscms.org\/storage\/public\/Plupload\/2014-11-15\/21\/2_39085467abdc00e75.jpg\" alt=\"\" width=\"600\" height=\"375\" \/><\/p>\r\n<p><!-- pagebreak --><\/p>\r\n<p><img src=\"http:\/\/cscms.org\/storage\/public\/Plupload\/2015-03-01\/08\/2_052154f2ac21d6849.jpg\" alt=\"\" width=\"800\" height=\"450\" \/><\/p>",
		    "draft": "0",
		    "short_content": "<p><img src=\"http:\/\/cscms.org\/storage\/public\/Plupload\/2014-11-15\/21\/2_39085467abdc00e75.jpg\" alt=\"\" width=\"600\" height=\"375\" \/><\/p>\r\n<p>",
		    "sections": [
		        "2"
		    ],
		    "tags": [
		        "CMS"
		    ],
		    "comments_count": 1
		}
	</script>
</article>
```
Все технические и семантические данные весьма компактно поместились, рендерится это с помощью достаточно простого веб-компонента.
Копипастить веб-компонент сюда не буду, можно найти [здесь](https://github.com/nazar-pc/CleverStyle-CMS/tree/master/components/modules/Blogs/includes/html/cs-blogs-post).

**Comment by ParkFramework** [comment]
Да, выглядит нормально.

Кстати есть возможность в кастом-свойствах использовать типы из словарей, это дает возможность расширять типы (классы) словарей.
Например в класс ``BlogPosting`` добавить поле ``user``, вот так:
```
<script type="application/ld+json">
{
    "@context":
    {
        "@vocab" : "https://schema.org",
        "user"   : ""
    },
    "@type" : "BlogPosting",
    "url"   : "/",
    "user"  :
    {
    	"@type" : "Person",
    	"name"  : "nazarpc"
    }
}
</script>
```

По поводу тест сайта, очень советую отдельный домен, убрать там Open Graph разметку весь статик HTML, оставить только JSON-LD.
Это будет более чистый эксперимент, который многое покажет, например есть риск что в снипетах выдачи будет HTML, вместо текст контента, как-то так ``<p><img src=....``

Но думаю все будет хорошо! )

**Comment by nazar-pc** [comment]
Хм... что-то я не совсем понял, зачем это может быть здесь? То есть если с постом - мне же интересно указать что это именно автор данного поста или вы о каком-то другом сценарии?

И да, Google учитывает Open Graph, но в первую очередь всё-таки JSON-LD. По поводу HTML в сниппетах - либо оставят, либо вырежут совсем, оставив текст (вероятнее), они же тоже не дураки там, наверняка предусмотрели)

**Comment by ParkFramework** [comment]
Да, конечно вместо ``user`` нужно использовать ``author``.
Я просто хотел показать в примере, что гугл анализирует кастом-поля а не просто их игнорирует.
Если кастом-поле будет объектом, с указанным типом из словаря, он будет иметь семантик смысл, и на оборот если объект будет без указания типа, тогда будет ошибка валидации, вот пример:
```
<script type="application/ld+json">
{
    "@context":
    {
        "@vocab" : "https://schema.org",
        "user"   : ""
    },
    "@type" : "BlogPosting",
    "url"   : "/",
    "user"  :
    {
    	"name"  : "nazarpc"
    }
}
</script>
```
Ошибка ``Unspecified type``, потому что объект ``user`` имеет поле ``name`` но не указан тип ``Person``. 

Не факт что гугл удалит HTML из текст строки, дело в том что свойство ``articleBody`` имеет тип ``text`` и во всех примерах JSON-LD имеет текст строки без HTML разметки, по этому возможно что они ``text`` значения не фильтруют от HTML, воспринимают как есть.

В общем чего гадать, проще сделать тест сайт, Open Graph убрать нужно потому что вы не сможете понять откуда гугл взял описания страницы из Open Graph или из meta тегов или из JSON-LD, по этому лучше делать все на чистом JSON-LD.

**Comment by nazar-pc** [comment]
Мда, по поводу анализа полей интересно, тоже обратил внимания, но как-то не придал значения. Стандарт стандартом, а правила у каждого свои. Прямо как с OAuth2 - в мелочах, но всем нужно отличиться)

**Comment by ParkFramework** [comment]
Да, у каждого свои тараканы, вот например валидатор Яндекса, ругается на кастом
-поля которые объявлены в контексте.

https://webmaster.yandex.ua/microtest.xml

По этому я говорил что нужны эксперименты на тест сайте )

**Comment by nazar-pc** [comment]
Яндекс разочаровал, ему и конечный слэш давай в `@vocab`, и кастомные поля не нравятся... Отписался одному из сотрудников Яндекса, посмотрим, к чему это приведет)

**Comment by ParkFramework** [comment]
Я уже спрашивал на stackoverflow, там два ответа они сходятся на том что валидаторы, выдают ошибки, но они не влияют на индексирования.

http://stackoverflow.com/questions/29480115/json-ld-additional-properties-that-are-not-in-the-dictionary-schema-org

Ответы на вопросы про JSON-LD лучше искать на англ ресурсах, в рунете эта тема редкость.

**Comment by ParkFramework** [comment]
Яндекс, понимает кастом-поля, если в контексте указать null, вот так
```
<script type="application/ld+json">
{
    "@context":
    {
        "@vocab" : "http://schema.org/",
        "user"   : null
    },
    "@type" : "BlogPosting",
    "url"   : "/",
    "user"  :
    {
        "@type" : "Person",
        "name"  : "nazarpc"
    }
}
</script>
```
Но тогда ругается гугл валидатор )

**Comment by nazar-pc** [comment]
Да я уже проверил, короче, будем пока игнорировать баги Яндекса, у них валидатор не информативный, но судя по тому что он выдает, кроме полей, которые ему не нравятся остальные он должен кушать нормально. Посмотрим.

**Comment by ParkFramework** [comment]
Ок, если сделаете тест сайт, дайте ссылку, интересно будет посмотреть на выдачу в поисковиах.

**Comment by nazar-pc** [comment]
В целом вот: https://www.google.com/search?q=site%3Acherrytea.org
На одном из сайтов уже стоит новая версия блога. Страницы в выдаче с `CherryTea.org - не словом, а ділом! [beta]` - старые, без - с обновленного сайта. Так что всё хорошо, Google индексирует и понимает. Яндекс, несмотря на то, что уже больше недели прошло, выдает устаревшую информацию. Посмотрим, может через месяц и забредет на сайт)

Эксперимент моно считать удачным, дальше буду работать над переводом на JSON-LD + Web Components фотогаллереи, магазина, и прочих модулей.

**Comment by ParkFramework** [comment]
Хороший сайт.

Но я уверен что снипеты в выдаче гугла, строятся на основе указанного вами content в meta og:description, нельзя это считать результатом JSON-LD.

**Comment by nazar-pc** [comment]
А судя по их анализатору разметки Open Graph всё же второй по приоритету, может для краткого текста и берут `og:description`, это более релевантно, чем полная статья. В любом случае для блога сниппет большой не сделаешь (что интересно, для краткого описание нет специального поля), вот будет интересно на интернет-магазине результат посмотреть, либо ещё чем-то таком, что преоставляет больше информации, которую можно вынести на страницу результатов поиска.

Код сайта, к стати, открыт: https://github.com/nazar-pc/CherryTea.org
Позже будет информация о том, что там да как, можно будет либо внести изменения, либо поднять себе аналогичный, но, к примеру, локализированный сайт.

**Comment by ParkFramework** [comment]
Да, будет интересно посмотреть на результат где будет явно видно что результат индексирования был на основе JSON-LD, к сожалению у меня руки все не доходят сделать свой тест сайт.

Анализатор гугла показывает ``articleBody:	<p><img src="``, т.е контент с HTML разметкой
Я задал этот вопрос знатокам разметки гугла, вот ссылка
https://productforums.google.com/d/msg/webmaster-ru/fud9P2l-Oek/auwXBZY6-vQJ

**Comment by nazar-pc** [comment]
Потому что я это в JSON-LD разметке указал, что указал то он и показывает.

**Comment by ParkFramework** [comment]
Да, все правильно, но это нужно учитывать, если гугл в выдаче удаляет HTML код, значит ненужно дублировать этот контент без HTML кода в meta тегах.

Мне во многом JSON-LD нравится имено тем что ненужно дублировать контент, для роботов и для JS движка сайта.
Если гугл не удаляет HTML код, значит нужно будет дублировать, в meta тегах тот же контент но без HTML кода.

**Comment by nazar-pc** [comment]
Я это дублирую в основном для Facebook, vk.com и подобных.
Если бы все понимали canonical мета-тэг, alternate, Vary заголовок (что и поисковых систем касается) - жить было бы гораздо проще, а так имеем что имеем, приходится подстраиваться. Не под всех, но хоть под самых крупных.

Движок много семантических вещей старается учитывать, особенно связанных с многоязычностью - меняется и интерфейс, и весь контент. Всевозможные HTTP заголовки учитываются при выборе языка, но нет же, вместо Accept-Language Facebook присылает мне X-Facebook-Locale, и полностью игнорирует canonical, как и alternate, впрочем, чтоб его... Вот и приходится разные хаки применять, дублировать данные.

**Comment by ParkFramework** [comment]
Я это все понимаю, но не все можно дублировать, например страница списка товаров или дерево комментариев, все это в мета теги не засунешь, поисковик будет брать то что указано в JSON-LD, и если там HTML, который он возможно не удаляет, то выдача результата может быть не красивой.

**Comment by ParkFramework** [comment]
Я сделал поиск запрос, текста который есть только в JSON-LD, все отлично отработало, гугл выдал снипет без HTML
https://www.google.com.ua/webhp?ie=UTF-8#q=site:cherrytea.org+%D1%89%D0%BE%D0%B1+%D1%86%D0%B5+%D0%B2%D1%81%D0%B5+%D0%B4%D0%B0%D1%80%D1%83%D0%B2%D0%B0%D1%82%D0%B8+%D0%94%D1%8F%D0%BA%D1%83%D1%94%D0%BC%D0%BE

Текст запрос ``щоб це все дарувати Дякуємо`` в JSON-LD ``щоб це все дарувати.<\/p>\r\n<p>Дякуємо``
Теперь смело можно заявлять что эксперимент прошел удачно :+1:

**Comment by nazar-pc** [comment]
Круто, спасибо за информацию!

**Comment by ParkFramework** [comment]
К сожалению я ошибся, текст был не только в JSON-LD, но и в ``og:description`` там он без HTML.

Я так же посмотрел на выдачу, демо страницы Ewa Gasperowicz, к сожалению Гугл вобще ничего не понял из разметки JSON-LD.

https://www.google.com.ua/#q=site:polymerlabs.github.io%2Fstructured-data-web-components%2Fdemo%2Fcombined-demo.html

Я конечно оптимист, но радостных новостей пока нет :)

**Comment by ParkFramework** [comment]
Проверил как работает поиск гугла, на вашем сайте в [статье](https://cleverstyle.org/ru/%D0%91%D0%BB%D0%BE%D0%B3%D0%B8/%D0%9F%D0%BE%D1%87%D0%B5%D0%BC%D1%83_cs_Singleton_%D0%B2_CleverStyle_Framework_%D1%8D%D1%82%D0%BE_%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%BE:8) есть слова `Dependency Injection` но гугл их [не найдет](https://www.google.com.ua/#q=site:cleverstyle.org+Dependency+Injection) он может найти только те слова которые есть в мета тегах [например](https://www.google.com.ua/#q=site:cleverstyle.org+Singleton) `Singleton`
Весь ваш контент в теге `<script type="application/ld+json">` гугл не находит.

**Comment by nazar-pc** [comment]
Печально, попробую почитать что нового в этом смысле в Google, может ему что не нравится.

**Comment by ParkFramework** [comment]
На сегодня они поддерживают только короткий список `Content Typ` 
[вот таблица](https://developers.google.com/search/docs/guides/mark-up-content)
